-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "basePrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "colors" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "gainFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "gallery" TEXT[] DEFAULT ARRAY[]::TEXT[];
